### ISSUE TITLE
AttributeError: module 'tensorpack.dataflow.dataset' has no attribute 'customData'

### ISSUE THREAD

**Issue by larkhu** [wuyuebupt/MSCeleb1MTensorflowModel#1]
How to solve the problem 
AttributeError: module 'tensorpack.dataflow.dataset' has no attribute 'customData'

**Comment by wuyuebupt** [comment]
@larkhu use this version of tensorpack https://github.com/wuyuebupt/tensorpack

**Comment by wuyuebupt** [comment]
@larkhu do you solve the problem?
